name: Grid CI
on: [pull_request]
jobs:
  JSBuild:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.16.1]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Kahuna
        working-directory: ./kahuna
        run: |
          npm install
          npm test
      - name: Image Counter Lambda
        working-directory: ./image-counter-lambda
        run: |
          npm install
          npm test
      - name: S3Watcher
        working-directory: ./s3watcher/lambda
        run: |
          npm install
          npm run build
      - name: Reaper
        working-directory: ./reaper
        run: |
          npm install
          npm run riffraff-artefact
  ScalaBuild:
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: elasticsearch:7.5.2
        # Wait for elasticsearch to report healthy before continuing.
        # see https://github.com/actions/example-services/blob/master/.github/workflows/postgres-service.yml#L28
        options: -e "discovery.type=single-node" --expose 9200 --health-cmd "curl localhost:9200/_cluster/health" --health-interval 10s --health-timeout 5s --health-retries 10
      localstack:
        image: localstack/localstack:0.11.0
        env:
          SERVICES: kinesis,dynamodb
          DEFAULT_REGION: eu-west-1
          KINESIS_ERROR_PROBABILITY: 0.0
          PORT_WEB_UI: 5050
        ports:
          - 5050:5050
          - 4566:4566
        options: >-
          --health-cmd "curl localhost:5050/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    steps:
    - uses: actions/checkout@v1
    - name: Cache SBT ivy cache
      uses: actions/cache@v1
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}
    - name: Cache SBT coursier cache
      uses: actions/cache@v1
      with:
        path: ~/.coursier/cache
        key: ${{ runner.os }}-sbt-coursier-cache-${{ hashFiles('**/build.sbt') }}
    - name: Cache SBT
      uses: actions/cache@v1
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: SBT
      env:
        USE_DOCKER_FOR_TESTS: false
        ES6_TEST_URL: http://elasticsearch:9200
        LOCALSTACK_ENDPOINT: http://localstack:4566
      run: sbt clean compile test
